@startuml


[*] --> INITIATED
CLOSED --> [*]

INITIATED : Shop API
INITIATED -> FILE_UPLOADED : загрузить файл
FILE_UPLOADED : 3d file storage
FILE_UPLOADED -> SUBMITTED : пользователь нажал кнопку Создать заказ
SUBMITTED : Shop API
SUBMITTED -> PRICE_CALCULATED : передать заказ на расчет стоимости
PRICE_CALCULATED : Mes API
PRICE_CALCULATED -> MANUFACTURING_APPROVED : стоимость расчитана
MANUFACTURING_APPROVED : CRM API
MANUFACTURING_APPROVED -> MANUFACTURING_STARTED
MANUFACTURING_STARTED : Mes API
MANUFACTURING_STARTED -> MANUFACTURING_COMPLETED 
MANUFACTURING_COMPLETED : Mes API
MANUFACTURING_COMPLETED -> PACKAGING 
PACKAGING : Mes API
PACKAGING -> SHIPPED 
SHIPPED : Mes API
SHIPPED -> CLOSED 
CLOSED : Mes API

@enduml